import nodemailer, { type Transporter } from "nodemailer";
import type { SavedContactMessage } from "./contact-store";
import { logger } from "./logger";

/**
 * Notification email for contact messages, sent through the site's own
 * mailbox over SMTP.
 *
 * Configuration comes from the environment (Replit Secrets on the deployment);
 * nothing is hard-coded and nothing is committed:
 *
 *   SMTP_HOST          mail server, e.g. the hosting account's mail host
 *   SMTP_PORT          465 (implicit TLS, the default) or 587 (STARTTLS)
 *   SMTP_SECURE        "true" for implicit TLS; defaults to true on port 465
 *   SMTP_USER          the site mailbox login, usually the full address
 *   SMTP_PASS          its password
 *   CONTACT_FROM       the address the notification is sent from; defaults to SMTP_USER
 *   CONTACT_FROM_NAME  display name for that address; defaults to "CurryControls.com contact form"
 *   CONTACT_TO         where the notification goes; one address or a comma-separated list
 *
 * With SMTP_HOST or CONTACT_TO unset the mailer is disabled: messages are
 * still stored and the API reports them as stored rather than emailed.
 */

type MailerConfig = {
  host: string;
  port: number;
  secure: boolean;
  user: string | undefined;
  pass: string | undefined;
  from: string;
  fromName: string;
  to: string[];
};

export type MailerStatus = { enabled: true } | { enabled: false; reason: string };

const SEND_TIMEOUT_MS = 20_000;

function readConfig(): MailerConfig | { reason: string } {
  const env = process.env;
  const host = env["SMTP_HOST"]?.trim();
  const to = (env["CONTACT_TO"] ?? "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
  const user = env["SMTP_USER"]?.trim() || undefined;
  const from = env["CONTACT_FROM"]?.trim() || user;

  if (!host) return { reason: "SMTP_HOST is not set" };
  if (to.length === 0) return { reason: "CONTACT_TO is not set" };
  if (!from) return { reason: "CONTACT_FROM (or SMTP_USER) is not set" };

  const port = Number(env["SMTP_PORT"] ?? 465);
  if (!Number.isInteger(port) || port <= 0) return { reason: `SMTP_PORT "${env["SMTP_PORT"]}" is invalid` };

  const secureRaw = env["SMTP_SECURE"]?.trim().toLowerCase();
  const secure = secureRaw ? secureRaw === "true" || secureRaw === "1" : port === 465;

  return {
    host,
    port,
    secure,
    user,
    pass: env["SMTP_PASS"],
    from,
    fromName: env["CONTACT_FROM_NAME"]?.trim() || "CurryControls.com contact form",
    to,
  };
}

let cached: { config: MailerConfig; transporter: Transporter } | null = null;

function getTransport(): { config: MailerConfig; transporter: Transporter } | { reason: string } {
  if (cached) return cached;
  const config = readConfig();
  if ("reason" in config) return config;

  const transporter = nodemailer.createTransport({
    host: config.host,
    port: config.port,
    secure: config.secure,
    auth: config.user ? { user: config.user, pass: config.pass ?? "" } : undefined,
    connectionTimeout: 10_000,
    greetingTimeout: 10_000,
    socketTimeout: 15_000,
  });

  cached = { config, transporter };
  return cached;
}

export function mailerStatus(): MailerStatus {
  const t = getTransport();
  return "reason" in t ? { enabled: false, reason: t.reason } : { enabled: true };
}

/** Header values must not carry line breaks; everything else nodemailer encodes. */
function headerSafe(value: string): string {
  return value.replace(/[\r\n]+/g, " ").trim();
}

function formatMessage(msg: SavedContactMessage): string {
  const rows: Array<[string, string | undefined]> = [
    ["Name", msg.name],
    ["Company / organization", msg.company],
    ["Email", msg.email],
    ["Phone", msg.phone],
    ["Topic", msg.topic],
    ["Subject", msg.subject],
    ["Sent from", msg.pagePath],
    ["Received", msg.createdAt.toISOString()],
    ["Message id", msg.id],
  ];
  const header = rows
    .filter((row): row is [string, string] => Boolean(row[1]))
    .map(([label, value]) => `${label}: ${value}`)
    .join("\n");

  return [
    "A message was sent through the CurryControls.com contact form.",
    "",
    header,
    "",
    "Message:",
    "",
    msg.message,
    "",
    "--",
    "Reply to this email to answer the sender directly.",
    "This notification was generated by the CurryControls.com contact form.",
  ].join("\n");
}

/**
 * Sends the owner notification. Resolves when the mail server has accepted the
 * message; rejects on any failure, including the send timeout, so the caller
 * can record the outcome against the stored message.
 */
export async function sendContactNotification(msg: SavedContactMessage): Promise<void> {
  const t = getTransport();
  if ("reason" in t) throw new Error(`Mailer disabled: ${t.reason}`);

  const subjectCore = headerSafe(msg.subject || msg.topic || "New message");
  const subject = `[CurryControls.com] ${subjectCore} — from ${headerSafe(msg.name)}`;

  const send = t.transporter.sendMail({
    from: { name: t.config.fromName, address: t.config.from },
    to: t.config.to,
    replyTo: { name: headerSafe(msg.name), address: msg.email },
    subject,
    text: formatMessage(msg),
  });

  let timer: ReturnType<typeof setTimeout> | undefined;
  const timeout = new Promise<never>((_, reject) => {
    timer = setTimeout(() => reject(new Error(`Send timed out after ${SEND_TIMEOUT_MS} ms`)), SEND_TIMEOUT_MS);
  });

  try {
    const info = await Promise.race([send, timeout]);
    logger.info({ id: msg.id, accepted: info.accepted.length }, "Contact: notification sent");
  } finally {
    if (timer) clearTimeout(timer);
  }
}
